"""
output/briefing.py
──────────────────
Format 4: Structured Briefing — top-N key papers with 3-line summaries.
Owned by Devang.

Produces a structured markdown briefing:
  - Executive summary of the research area
  - Top-N papers ranked by relevance, each with a 3-line summary
  - Quick-reference stats table
  - Key contradictions highlight (if any)

This is the Phase 1 output — simpler than the other formats, 
implemented first so the pipeline is demoable end-to-end in Week 2.
"""

import json
import os
from typing import Optional

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, SystemMessage

from core.context import SharedContext

_LLM = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.4,
    max_tokens=4096,
    timeout=60,
    max_retries=3,
)

TOP_N_DEFAULT = 10  # Papers to include in the briefing


def _call_llm(prompt: str) -> Optional[str]:
    try:
        response = _LLM.invoke([HumanMessage(content=prompt)])
        return response.content.strip()
    except Exception as exc:
        print(f"[Briefing] LLM call failed: {exc}")
        return None


def _generate_executive_summary(topic: str, papers: list[dict], extractions: list[dict]) -> str:
    """Generate a 3-4 sentence executive summary of the research area."""
    slim_extractions = [
        {
            "title": e.get("title", ""),
            "year": e.get("year"),
            "methodology_cluster": e.get("methodology_cluster", ""),
            "key_finding": e.get("key_finding", ""),
        }
        for e in extractions[:15]
    ]

    prompt = f"""You are writing an executive summary for a literature briefing on: "{topic}"

Based on these {len(extractions)} analyzed papers:
{json.dumps(slim_extractions, indent=2)}

Write a 3-4 sentence executive summary covering:
1. What this research area is about and why it matters
2. The dominant methodological approaches found
3. The current state of the field and open challenges

Be concise, authoritative, and specific. No bullet points — flowing prose only.
Return ONLY the summary text, no headers or labels."""

    result = _call_llm(prompt)
    return result or f"Literature review on {topic} covering {len(extractions)} papers across multiple methodological approaches."


def _generate_paper_summary(paper: dict, extraction: dict) -> str:
    """Generate a tight 3-line summary for a single paper."""
    prompt = f"""Summarize this research paper in exactly 3 concise lines (not bullet points):
Line 1: What problem it solves and the core method used.
Line 2: The key result or finding (include specific metrics if available).
Line 3: Why this paper matters / its impact on the field.

Paper: {paper.get('title', '')} ({paper.get('year', 'N/A')})
Abstract: {(paper.get('abstract', '') or '')[:800]}
Methodology: {extraction.get('methodology', 'not specified')}
Key finding: {extraction.get('key_finding', 'not specified')}
Metric: {extraction.get('reported_metric', 'not specified')}

Return ONLY the 3 lines, numbered 1. 2. 3."""

    result = _call_llm(prompt)
    if result:
        return result
    # Fallback: construct from extraction data
    lines = [
        f"1. {extraction.get('methodology', 'Methodology not specified.')}",
        f"2. {extraction.get('key_finding', 'Key finding not available.')}",
        f"3. Dataset: {extraction.get('dataset_used', 'not specified')}. Metric: {extraction.get('reported_metric', 'not specified')}.",
    ]
    return "\n".join(lines)


def generate(context: SharedContext, top_n: int = TOP_N_DEFAULT) -> str:
    """
    Generate a structured briefing document in Markdown format.

    Args:
        context: SharedContext with extracted_knowledge populated.
        top_n:   Number of papers to include (default 10).

    Returns:
        Markdown string of the full briefing.
    """
    topic = context.topic
    papers = context.user_confirmed_papers
    extractions = context.extracted_knowledge
    contradictions = context.contradiction_report
    timeline = context.paradigm_timeline

    if not papers or not extractions:
        return f"# Literature Briefing: {topic}\n\n*No papers available for briefing.*"

    # Build a lookup: paperId → extraction
    extraction_map = {e.get("paperId", ""): e for e in extractions}

    # Pick top-N papers by relevance score
    sorted_papers = sorted(papers, key=lambda p: p.get("relevance_score", 0.0), reverse=True)
    top_papers = sorted_papers[:top_n]

    lines = []

    # ── Header ──────────────────────────────────────────────────────────────
    lines.append(f"# Literature Briefing: {topic}")
    lines.append(f"\n*{len(papers)} papers analyzed · Top {min(top_n, len(top_papers))} shown · Generated by Literature Analysis System*\n")
    lines.append("---")

    # ── Executive Summary ────────────────────────────────────────────────────
    lines.append("\n## Executive Summary\n")
    summary = _generate_executive_summary(topic, papers, extractions)
    lines.append(summary)

    # ── Quick Stats ──────────────────────────────────────────────────────────
    lines.append("\n## At a Glance\n")
    years = [p.get("year") for p in papers if p.get("year")]
    clusters = list(set(e.get("methodology_cluster", "other") for e in extractions))
    major_contradictions = [c for c in contradictions if c.get("severity") == "major"]

    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Papers analyzed | {len(papers)} |")
    lines.append(f"| Year range | {min(years) if years else 'N/A'} – {max(years) if years else 'N/A'} |")
    lines.append(f"| Methodology clusters | {', '.join(clusters)} |")
    lines.append(f"| Contradictions found | {len(contradictions)} ({len(major_contradictions)} major) |")
    lines.append(f"| Paradigm shifts | {len(timeline)} |")

    # ── Top Papers ───────────────────────────────────────────────────────────
    lines.append(f"\n## Top {len(top_papers)} Papers\n")

    for i, paper in enumerate(top_papers, 1):
        pid = paper.get("paperId") or paper.get("arxiv_id", "")
        ext = extraction_map.get(pid, {})

        title = paper.get("title", "Untitled")
        year = paper.get("year", "N/A")
        authors = paper.get("authors", [])
        author_str = ", ".join(authors[:2]) + (" et al." if len(authors) > 2 else "")
        citations = paper.get("citationCount", 0)
        cluster = ext.get("methodology_cluster", "—")
        relevance = paper.get("relevance_score", 0.0)
        pdf_url = paper.get("pdf_url")
        confidence = ext.get("confidence_score", 0.0)

        # Paper header
        if pdf_url:
            lines.append(f"### {i}. [{title}]({pdf_url}) ({year})")
        else:
            lines.append(f"### {i}. {title} ({year})")

        lines.append(f"*{author_str}* · {citations:,} citations · Cluster: `{cluster}` · Relevance: {relevance:.2f}")

        if confidence < 0.4:
            lines.append(f"\n> ⚠️ **Low extraction confidence** ({confidence:.2f}): {ext.get('low_confidence_reason', 'abstract may be incomplete')}")

        lines.append("")

        # 3-line summary
        summary_text = _generate_paper_summary(paper, ext)
        lines.append(summary_text)
        lines.append("")

        # Key metadata row
        dataset = ext.get("dataset_used", "not specified")
        metric = ext.get("reported_metric", "not specified")
        if dataset != "not specified" or metric != "not specified":
            lines.append(f"**Dataset:** {dataset} · **Metric:** {metric}")
            lines.append("")

    # ── Contradictions ───────────────────────────────────────────────────────
    if contradictions:
        lines.append("---")
        lines.append("\n## Key Contradictions\n")
        major = [c for c in contradictions if c.get("severity") == "major"]
        minor = [c for c in contradictions if c.get("severity") == "minor"]

        if major:
            lines.append("### Major Contradictions\n")
            for c in major:
                lines.append(f"**{c.get('paper_a_title', '?')} ({c.get('paper_a_year', '?')})** vs **{c.get('paper_b_title', '?')} ({c.get('paper_b_year', '?')})**")
                lines.append(f"- Paper A claims: {c.get('claim_a', '—')}")
                lines.append(f"- Paper B claims: {c.get('claim_b', '—')}")
                lines.append(f"- *{c.get('reasoning', '')}*")
                lines.append("")

        if minor:
            lines.append(f"### Minor Contradictions ({len(minor)})\n")
            for c in minor:
                lines.append(f"- **{c.get('paper_a_title', '?')[:50]}** vs **{c.get('paper_b_title', '?')[:50]}**: {c.get('reasoning', '—')}")

    # ── Timeline Highlights ───────────────────────────────────────────────────
    if timeline:
        lines.append("\n---")
        lines.append("\n## Paradigm Shift Highlights\n")
        paradigm_shifts = [e for e in timeline if e.get("impact") == "paradigm-shift"]
        display_events = paradigm_shifts if paradigm_shifts else timeline[:5]

        for event in display_events:
            impact_icon = {"paradigm-shift": "🔴", "significant": "🟡", "incremental": "🟢"}.get(event.get("impact", ""), "⚪")
            lines.append(f"**{event.get('year', '?')}** {impact_icon} {event.get('shift_description', '—')}")
            lines.append(f"  *Key paper: {event.get('key_paper', '—')}*")
            lines.append("")

    lines.append("\n---")
    lines.append("\n*Generated by Literature Analysis System · Showcase Agent*")

    return "\n".join(lines)
