from dataclasses import dataclass, field
from typing import Any

@dataclass
class SharedContext:
    # ── Input ────────────────────────────────────────────────────────────────
    topic: str = ""
    query_variants: list[str] = field(default_factory=list)
    # Generated by Retriever (Gemini expands topic into 3–4 search strings)

    # ── Retriever outputs ────────────────────────────────────────────────────
    raw_papers: list[dict] = field(default_factory=list)
    # Keys per paper: title, abstract, year, authors, paperId,
    #                 citationCount, references, source, relevance_score

    deduplicated_papers: list[dict] = field(default_factory=list)
    # Same schema as raw_papers; duplicates removed via embedding similarity

    paper_embeddings: dict[str, list[float]] = field(default_factory=dict)
    # Maps paperId → embedding vector (text-embedding-3-small, dim=1536)
    # Populated by Retriever during dedup; consumed by Analyst for clustering.
    # ChromaDB persists these to disk — this field is the in-memory
    # counterpart so agents don't recompute embeddings mid-pipeline.

    # ── HITL checkpoint ──────────────────────────────────────────────────────
    user_confirmed_papers: list[dict] = field(default_factory=list)
    # Subset of deduplicated_papers approved by user at the HITL screen

    # ── Analyst outputs ──────────────────────────────────────────────────────
    extracted_knowledge: list[dict] = field(default_factory=list)
    # Per-paper: {paperId, methodology, finding, dataset, metric,
    #             methodology_cluster, confidence_score}

    contradiction_report: list[dict] = field(default_factory=list)
    # Per contradiction: {paper_a, paper_b, claim_a, claim_b,
    #                     reasoning, severity ('minor'|'major')}

    paradigm_timeline: list[dict] = field(default_factory=list)
    # Per shift: {year, shift_description, key_paper, impact}

    # ── Showcase / output ────────────────────────────────────────────────────
    output_format: str = ""
    # One of: "written_review" | "knowledge_map" | "timeline" | "briefing"

    final_output: Any = None

    # ── Pipeline metadata ────────────────────────────────────────────────────
    pipeline_status: str = "idle"
    # Stages: "idle" → "retrieving" → "awaiting_hitl" → "analysing"
    #         → "showcasing" → "done" | "error"
    # Devang's HITL logic gates on "awaiting_hitl"; Streamlit
    # session_state mirrors this to control st.stop() timing.

    errors: list[dict] = field(default_factory=list)
    # Each entry: {stage, message, timestamp, recoverable: bool}
    # Populated by any agent; Showcase surfaces non-recoverable ones to UI.